// Mocks generated by Mockito 5.3.0 from annotations
// in core/test/data/repositories/tv_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/data/datasources/tv_datasource/tv_local_data_source.dart'
    as _i6;
import 'package:core/data/datasources/tv_datasource/tv_remote_data_source.dart'
    as _i3;
import 'package:core/data/models/tv_series_model/tv_detail_model.dart' as _i2;
import 'package:core/data/models/tv_series_model/tv_model.dart' as _i5;
import 'package:core/data/models/tv_series_model/tv_table.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTVDetailResponse_0 extends _i1.SmartFake
    implements _i2.TVDetailResponse {
  _FakeTVDetailResponse_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TVRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRemoteDataSource extends _i1.Mock
    implements _i3.TVRemoteDataSource {
  MockTVRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TVModel>> getTVOnTheAir() =>
      (super.noSuchMethod(Invocation.method(#getTVOnTheAir, []),
              returnValue: _i4.Future<List<_i5.TVModel>>.value(<_i5.TVModel>[]))
          as _i4.Future<List<_i5.TVModel>>);
  @override
  _i4.Future<List<_i5.TVModel>> getPopularTV() =>
      (super.noSuchMethod(Invocation.method(#getPopularTV, []),
              returnValue: _i4.Future<List<_i5.TVModel>>.value(<_i5.TVModel>[]))
          as _i4.Future<List<_i5.TVModel>>);
  @override
  _i4.Future<List<_i5.TVModel>> getTopRatedTV() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTV, []),
              returnValue: _i4.Future<List<_i5.TVModel>>.value(<_i5.TVModel>[]))
          as _i4.Future<List<_i5.TVModel>>);
  @override
  _i4.Future<_i2.TVDetailResponse> getDetailTV(int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetailTV, [id]),
              returnValue: _i4.Future<_i2.TVDetailResponse>.value(
                  _FakeTVDetailResponse_0(
                      this, Invocation.method(#getDetailTV, [id]))))
          as _i4.Future<_i2.TVDetailResponse>);
  @override
  _i4.Future<List<_i5.TVModel>> getTVRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTVRecommendations, [id]),
              returnValue: _i4.Future<List<_i5.TVModel>>.value(<_i5.TVModel>[]))
          as _i4.Future<List<_i5.TVModel>>);
  @override
  _i4.Future<List<_i5.TVModel>> searchTV(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTV, [query]),
              returnValue: _i4.Future<List<_i5.TVModel>>.value(<_i5.TVModel>[]))
          as _i4.Future<List<_i5.TVModel>>);
}

/// A class which mocks [TVLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVLocalDataSource extends _i1.Mock implements _i6.TVLocalDataSource {
  MockTVLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> insertWatchlistTV(_i7.TVTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlistTV, [tv]),
          returnValue: _i4.Future<String>.value('')) as _i4.Future<String>);
  @override
  _i4.Future<String> removeWatchlistTV(_i7.TVTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistTV, [tv]),
          returnValue: _i4.Future<String>.value('')) as _i4.Future<String>);
  @override
  _i4.Future<_i7.TVTable?> getByIdTV(int? id) =>
      (super.noSuchMethod(Invocation.method(#getByIdTV, [id]),
              returnValue: _i4.Future<_i7.TVTable?>.value())
          as _i4.Future<_i7.TVTable?>);
  @override
  _i4.Future<List<_i7.TVTable>> getWatchlistTV() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTV, []),
              returnValue: _i4.Future<List<_i7.TVTable>>.value(<_i7.TVTable>[]))
          as _i4.Future<List<_i7.TVTable>>);
}
