// Mocks generated by Mockito 5.3.0 from annotations
// in core/test/presentation/pages/tv_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:core/domain/entities/tv_entities/tv.dart' as _i9;
import 'package:core/domain/entities/tv_entities/tv_detail.dart' as _i7;
import 'package:core/domain/usecases/tv_usecase/get_tv_detail.dart' as _i2;
import 'package:core/domain/usecases/tv_usecase/get_tv_recommendations.dart'
    as _i3;
import 'package:core/domain/usecases/tv_usecase/get_watchlist_status_tv.dart'
    as _i4;
import 'package:core/domain/usecases/tv_usecase/remove_watchlist_tv.dart'
    as _i6;
import 'package:core/domain/usecases/tv_usecase/save_watchlist_tv.dart' as _i5;
import 'package:core/presentation/provider/tv_series_provider/tv_detail_notifier.dart'
    as _i8;
import 'package:core/utils/state_enum.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTVDetail_0 extends _i1.SmartFake implements _i2.GetTVDetail {
  _FakeGetTVDetail_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetTVRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTVRecommendations {
  _FakeGetTVRecommendations_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetWatchlistStatusTV_2 extends _i1.SmartFake
    implements _i4.GetWatchlistStatusTV {
  _FakeGetWatchlistStatusTV_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTV_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistTV {
  _FakeSaveWatchlistTV_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTV_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistTV {
  _FakeRemoveWatchlistTV_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTVDetail_5 extends _i1.SmartFake implements _i7.TVDetail {
  _FakeTVDetail_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TVDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVDetailNotifier extends _i1.Mock implements _i8.TVDetailNotifier {
  MockTVDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVDetail get getTVDetail =>
      (super.noSuchMethod(Invocation.getter(#getTVDetail),
              returnValue:
                  _FakeGetTVDetail_0(this, Invocation.getter(#getTVDetail)))
          as _i2.GetTVDetail);
  @override
  _i3.GetTVRecommendations get getTVRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTVRecommendations),
              returnValue: _FakeGetTVRecommendations_1(
                  this, Invocation.getter(#getTVRecommendations)))
          as _i3.GetTVRecommendations);
  @override
  _i4.GetWatchlistStatusTV get getWatchlistStatusTV =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistStatusTV),
              returnValue: _FakeGetWatchlistStatusTV_2(
                  this, Invocation.getter(#getWatchlistStatusTV)))
          as _i4.GetWatchlistStatusTV);
  @override
  _i5.SaveWatchlistTV get saveWatchlistTV => (super.noSuchMethod(
          Invocation.getter(#saveWatchlistTV),
          returnValue:
              _FakeSaveWatchlistTV_3(this, Invocation.getter(#saveWatchlistTV)))
      as _i5.SaveWatchlistTV);
  @override
  _i6.RemoveWatchlistTV get removeWatchlistTV =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlistTV),
              returnValue: _FakeRemoveWatchlistTV_4(
                  this, Invocation.getter(#removeWatchlistTV)))
          as _i6.RemoveWatchlistTV);
  @override
  _i7.TVDetail get tvDetail => (super.noSuchMethod(Invocation.getter(#tvDetail),
          returnValue: _FakeTVDetail_5(this, Invocation.getter(#tvDetail)))
      as _i7.TVDetail);
  @override
  List<_i9.TV> get tvRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendations),
          returnValue: <_i9.TV>[]) as List<_i9.TV>);
  @override
  _i10.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  _i10.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedtoWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedtoWatchlist),
          returnValue: false) as bool);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchTVDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchTVDetail, [id]),
              returnValue: _i11.Future<void>.value(),
              returnValueForMissingStub: _i11.Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [tv]),
              returnValue: _i11.Future<void>.value(),
              returnValueForMissingStub: _i11.Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> removeWatchlist(_i7.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tv]),
              returnValue: _i11.Future<void>.value(),
              returnValueForMissingStub: _i11.Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(Invocation.method(#loadWatchlistStatus, [id]),
              returnValue: _i11.Future<void>.value(),
              returnValueForMissingStub: _i11.Future<void>.value())
          as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
