// Mocks generated by Mockito 5.3.0 from annotations
// in search/test/domain/usecases/search_tv_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/utils/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/entities/tv.dart' as _i6;
import 'package:tv_series/domain/entities/tv_detail.dart' as _i7;
import 'package:tv_series/domain/repositories/tv_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TVRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRepository extends _i1.Mock implements _i3.TVRepository {
  MockTVRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>> getTvOnTheAir() =>
      (super.noSuchMethod(Invocation.method(#getTvOnTheAir, []),
          returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.TV>>(
                  this, Invocation.method(#getTvOnTheAir, [])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.TV>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>> getPopularTV() =>
      (super.noSuchMethod(Invocation.method(#getPopularTV, []),
          returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.TV>>(
                  this, Invocation.method(#getPopularTV, [])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.TV>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>> getTopRatedTV() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTV, []),
          returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.TV>>(
                  this, Invocation.method(#getTopRatedTV, [])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.TV>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.TVDetail>> getDetailTV(int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetailTV, [id]),
          returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.TVDetail>>.value(
              _FakeEither_0<_i5.Failure, _i7.TVDetail>(
                  this, Invocation.method(#getDetailTV, [id])))) as _i4
          .Future<_i2.Either<_i5.Failure, _i7.TVDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>> getRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getRecommendations, [id]),
          returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.TV>>(
                  this, Invocation.method(#getRecommendations, [id])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.TV>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>> searchTV(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTV, [query]),
          returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.TV>>(
                  this, Invocation.method(#searchTV, [query])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.TV>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>> getWatchlistTV() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTV, []),
          returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.TV>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.TV>>(
                  this, Invocation.method(#getWatchlistTV, [])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.TV>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlistTV(
          _i7.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlistTV, [tv]),
              returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>(
                      this, Invocation.method(#saveWatchlistTV, [tv]))))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWatchlistTV(
          _i7.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistTV, [tv]),
              returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>(
                      this, Invocation.method(#removeWatchlistTV, [tv]))))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: _i4.Future<bool>.value(false)) as _i4.Future<bool>);
}
